// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkzpvfimhqippufgznbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrenB2ZmltaHFpcHB1Zmd6bmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjY0MDQsImV4cCI6MjA2OTYwMjQwNH0.i-rXjfgJyQIIJ2v8XCr1sc_LYpwQzy0Ju22llrKADp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});